version: '3'
services:
  mysql56:
    image: mysql:5.6
    volumes:
      - /var/lib/mysql56/data:/var/lib/mysql
      - /var/lib/mysql56/etc/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
  mysql80:
    image: mysql:8.0
    volumes:
      - /var/lib/mysql80/data:/var/lib/mysql
      - /var/lib/mysql80/etc/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
